create table personalities(
	id serial primary key,
	name varchar,
	history varchar
);

-- Generated by AI
INSERT INTO personalities (name, history) VALUES
("Abraham Lincoln", "16th President of the United States, known for leading the country during the Civil War and abolishing slavery."),
("Thomas Edison", "Prolific American inventor and businessman, known for developing the phonograph, the motion picture camera, and the electric light bulb."),
("Benjamin Franklin", "One of the Founding Fathers of the United States, renowned polymath, inventor, and diplomat."),
("George Washington", "First President of the United States and commanding general during the American Revolutionary War."),
("Albert Einstein", "Theoretical physicist known for developing the theory of relativity, one of the two pillars of modern physics."),
("Isaac Newton", "Influential scientist who formulated the laws of motion and universal gravitation."),
("Nikola Tesla", "Inventor and electrical engineer known for his contributions to the development of alternating current (AC) electrical systems."),
("Galileo Galilei", "Astronomer, physicist, and engineer, known for his pioneering use of the telescope and support of heliocentrism."),
("Marie Curie", "Physicist and chemist who conducted pioneering research on radioactivity, the first woman to win a Nobel Prize."),
("Leonardo da Vinci", "Renaissance polymath known for his contributions to art, science, and engineering, famous for paintings like 'Mona Lisa' and 'The Last Supper'."),
("Winston Churchill", "British Prime Minister during World War II, known for his leadership and oratory skills."),
("Mahatma Gandhi", "Leader of the Indian independence movement against British rule, known for his philosophy of nonviolent resistance."),
("Martin Luther King Jr.", "Civil rights leader who advocated for nonviolent resistance against racial segregation and inequality."),
("Nelson Mandela", "Anti-apartheid revolutionary and former President of South Africa, known for his role in ending apartheid and fostering reconciliation."),
("Cleopatra", "The last active ruler of the Ptolemaic Kingdom of Egypt, known for her intelligence, political acumen, and romantic liaisons with Julius Caesar and Mark Antony."),
("Julius Caesar", "Roman general and statesman who played a critical role in the events that led to the demise of the Roman Republic and the rise of the Roman Empire."),
("Alexander the Great", "King of Macedonia who created one of the largest empires in history by the age of thirty."),
("Aristotle", "Ancient Greek philosopher and polymath, student of Plato and teacher of Alexander the Great, known for his writings on many subjects."),
("Sigmund Freud", "Austrian neurologist and the founder of psychoanalysis, a clinical method for treating psychopathology through dialogue."),
("Mother Teresa", "Roman Catholic nun and missionary known for her charitable work with the poor and sick in Kolkata, India.")
;
